name: hacknlearn.in
pygments: true
exclude:
 - README.md
 - Procfile
 - Gemfile
 - Gemfile.lock
 - config.ru
 - vendor

title: Srikanth Venugopalan
description: "writes code, loves hacking.<br />From Chennai, India"

url: http://www.hacknlearn.in
permalink: pretty

twitter: stylish_steam
github: sriv